### ISSUE TITLE
Error upon trying to install package

### ISSUE THREAD

**Issue by sunyesta** [Nickuhhh/LayoutUtil#2]
![image](https://user-images.githubusercontent.com/21149042/181408838-2230c846-0502-4933-aade-edf0e3030a32.png)

![image](https://user-images.githubusercontent.com/21149042/181408711-dd8b4c74-beb6-4341-85de-1e5ea8a3b30e.png)

**Comment by ok-nick** [comment]
Sorry, I haven't yet released or published `v3.0.0` to `wally`, I'll try and get to it soon. I'm not sure if `wally` supports git branches as dependencies either, I don't think it does.

**Comment by sunyesta** [comment]
thanks for the info! So which version should I use? I've tried LayoutUtil = "ok-nick/LayoutUtil@2.0.0" but it gives me the same error.

**Comment by ok-nick** [comment]
`wally` wasn't around during that time so I never got the chance to upload a manifest for it. I believe someone uploaded an earlier version of `LayoutUtil` to the `wally` registry, but I think it was <v1. I'll release v3 tomorrow and remind you when I do. For now, you can probably just manually copy `LayoutUtil` into your packages folder. It seems `wally` doesn't support github dependencies atm.

**Comment by sunyesta** [comment]
alright, thanks so much!

**Comment by ok-nick** [comment]
Released under version `v3.0.0-rc.1`, you should be able to use it now.
