### ISSUE TITLE
Can't install it with wally

### ISSUE THREAD

**Issue by aykut92** [Nickuhhh/LayoutUtil#4]
I commented my other dependecies to test it.

[dependencies] 
#Knit = "sleitnick/knit@^1.4"
#Signal = "sleitnick/signal@1.2.1"
#Trove = "sleitnick/trove@0.5.0"
#Component = "sleitnick/component@2.4.6"
#Shake = "sleitnick/shake@0.1.7"
LayoutUtil = "ok-nick/layoututil@3.0.0-rc.1"

[INFO ] Updating package index https://github.com/UpliftGames/wally-index...
A dev dependency cannot be dependened upon by a non-dev dependency

**Comment by ok-nick** [comment]
I believe this issue has to do with [this PR](https://github.com/UpliftGames/wally/pull/75) in `wally`. `wally` hasn't seen a new release in over a year so this fix isn't yet published.

Someone suggested using `LayoutUtil` as a dev dependency which would work around the issue, though it isn't idiomatic. You can also reupload `LayoutUtil` without the dev dependency as a temporary fix.

**Comment by aykut92** [comment]
Oh, thanks! I will take a look.
